### PR TITLE
impl: Create .gitignore

### PR DESCRIPTION
**Pull request by apollac4**
Included frameworks and dependencies used; fixes issue #3

### CODE REVIEW

**Comment by apollac4** [comment]
Verified this will cause no merge errors and that it improves the readability of files on this GitHub repo

**Comment by sschafe** [comment]
Looks good. Looks like it won't cause any issues.

**Comment by sakibjabbar** [comment]
Checked .gitignore; everything looks good to me.

**Comment by dreaka17** [comment]
The gitignore looks good.

**Comment by coxender** [comment]
Looks good.

**Comment by jwalter26** [comment]
Approved by me.

**Review by dreaka17 — APPROVED** [review]

**Pull request merged**
