### PR TITLE
impl: Django Project File Setup

### PR DESCRIPTION
**Pull request by coxender**
Setup .gitignore and django project files for repo and remote server, to allow others to clone basic file structure.
fixes Issue #2

### CODE REVIEW

**Comment by apollac4** [comment]
Reviewed the implementation, looks great and doesn't cause errors

**Comment by dreaka17** [comment]
Project setup looks good

**Comment by sschafe** [comment]
Looks good. Doesn't look like it will cause any errors.

**Comment by coxender** [comment]
Basic file structure, should work so everyone has a proper local cloned django project

**Comment by sakibjabbar** [comment]
Reviewed; looks good

**Comment by jwalter26** [comment]
Looks good and seems it won't create any issues.

**Review by dreaka17 — APPROVED** [review]

**Pull request merged**
