### PR TITLE
Docs: INSTALL document

### PR DESCRIPTION
**Pull request by jwalter26**
Adds an installation guide for Muninn's packages, dependencies, and how to run the project locally for it to be worked on. Fixes issue #4.
@AndreakaJump

### CODE REVIEW

**Comment by dreaka17** [comment]
Install documentation looks good

**Comment by apollac4** [comment]
Reviewed the INSTALL doc, looks informative and good for the main branch

**Comment by sakibjabbar** [comment]
Reviewed; everything looks good

**Comment by sschafe** [comment]
Reads easy and understandable. Good job.

**Comment by coxender** [comment]
Reviewed, looks clear.

**Review by dreaka17 — APPROVED** [review]

**Pull request merged**
